### ISSUE TITLE
Finish wireframe

### ISSUE THREAD

**Issue by hansonnick25** [hansonnick25/movie-quiz#1]

**Comment by jdgiancola** [comment]
PAGE 1
![1](https://github.com/hansonnick25/movie-quiz/assets/135674863/9ee19749-0c23-4dc8-8261-28cfaa1a77e1)
PAGE 2
![Image](https://github.com/hansonnick25/movie-quiz/assets/135674863/dd8c7987-fef5-4194-8b8e-a56f5193a3c2)
PAGE 4
![3](https://github.com/hansonnick25/movie-quiz/assets/135674863/3c5bc8cc-f1d7-41af-95e1-c01fdd666a67)

**Comment by jdgiancola** [comment]
PAGE 3
![Image](https://github.com/hansonnick25/movie-quiz/assets/135674863/26982812-cd60-4d00-9384-39eed131a0e9)

**Comment by jdgiancola** [comment]
PAGE 3 (END)
![Image](https://github.com/hansonnick25/movie-quiz/assets/135674863/63ce3d89-66cf-4157-865b-765014150a52)
