### ISSUE TITLE
Finalize project idea

### ISSUE THREAD

**Issue by abdulsamedtma** [hansonnick25/movie-quiz#2]

**Comment by jdgiancola** [comment]
I made the wireframe as a guessing game multiple-choice quiz. The object is to look at the four movies, you are given the rank of a movie and you have to guess which one it is. If there aren't any objections this seems like a straight-forward thing we could accomplish in the time allotted.

**Comment by hansonnick25** [comment]
I agree with the wireframe and project idea, I think this seems like a good way for us to go forward

**Comment by abdulsamedtma** [comment]
I absolutely agree; that was extremely intelligent; nonetheless, let us keep in mind the timeline required for completion and presentation.

**Comment by hansonnick25** [comment]
The mockups look great general acceptance criteria below: 

GIVEN I am playing the movie-quiz game
WHEN I load the homepage
THEN it loads properly
WHEN I press Start
THEN the game begins
AND the first question pops up
AND I am presented with a Rotten Tomatoes (or IMDB) score and a list of 4 movies that it could possibly be
WHEN I select an answer
AND press Submit
THEN a review page pops up with a link to the movie trailer, a fun fact about the movie and whether or not you got the question right
WHEN you hit Continue
THEN the next question loads
OR the end of the quiz if you are at the final question
WHEN the end page of the quiz loads
THEN I see a list of High scores from LocalStorage
